class services:
    serviceDict = {
        "Lawn Care": """Wurk Services is run by local students who know the Barrington and Chicago land area. <br></br>
    Our team has the capability to meet all your common landscaping needs, to keep your lawn green and free of weeds, from: basic mowing to more complex tasks like tree removal and garden design. Our landscaping team takes pride in providing the barrington and the Chicago land area with local high quality landscaping services, maintenance, and design. <br></br>
    As our customers, you can be assured that you will receive the finest combination of lawn care, quality materials and highly trained local personnel. <br></br>
    We service properties in the Chicagoland area on a weekly basis, that allow us to keep your lawn green, healthy and free of weeds. Our grass cutting service includes cutting the lawn, edging, trimming and blowing. """,
        "Lawn Care Meta": """Wurk Services Has Been Continuously Providing Highest Rated Landscaping Services in Chicago, Barrington Il, 60007, 60010. Our services include landscaping services, lawn maintenance, 
        landscaping design, landscaping installation, sod for our clients in Chicago, Barrington. We are fully committed to providing top of the line landscape services to fit our client’s lifestyles.""",
        "Junk Removal": '''Wurk is a leading junk removal service, specializing in removing junk and clutter of all kinds. Contact us today to get your junk removed! Wurk Junk Removal Services can save you money over dumpster rentals, by charging you only for how much you need removed!. <br></br>
    Our Junk Removal Services and Haul Away Services is professional, affordable, and quick. There is no job too big or small. After removing your items, when possible we donate what we can, recycle what we can then dispose of the what needs to be eliminated. <br></br>
    While residential junk removal may seem like all you need is a little elbow grease, the reality is that quite often waste disposal can be dangerous. In addition to the known dangers of loose nails, broken boards, and sharp metal, hazardous chemicals may be found within the junk or waste that is being removed. Without proper protection, exposure to chemicals or other contaminants can be detrimental to your health. <br></br>
    Whether we are providing residential or commercial junk removal, Wurk Junk Removal Services always comes prepared. With hard hats, hazmat suits, and professional grade work masks, we can help you to safely take out the trash so that you can get back to your life. We can even help you with junk recycling if you have large amounts of metal, plastic, glass, or other recyclables.''',
        "Junk Removal Meta": "Meta: Wurk Services Has Been Continuously Providing Highest Rated Junk Removal Services in Chicago, Barrington Il, 60007, 60010. Our services include Junk Removal, Hauling Services, and Removing Junk Service for our clients in Chicago, Barrington. We are fully committed to making our client’s life easier buy offering affordable junk removal services.",
        "Painting and Staining": """Wurk Chicago Services is a professional painting company with many years of experience servicing the Chicagoland Area. We offer a wide range of painting services including interior and exterior painting, deck staining and restoration and remodeling.  <br></br>
    We have a very simple policy. Make sure every customer is Happy. Period. Our friendly customer service, humbling awards and numerous reviews have historically proven that our mission is succeeding. <br></br>
    If you are looking for an interior or an estimate that fits within your spending limits, click on the book now button below.""",
        "Painting and Staining Meta": ''' Wurk Services Has Been Continuously Providing Highest Rated Painting & Staining Services in Chicago, Barrington Il, 60007, 60010. Our services include Painting, Painter Services, and providing interior & exterior commercial & residential painter services for our clients in Chicago, Barrington. We are fully committed to making our client’s properties look better, with quality services.''',
        "Powerwashing": '''One of the services that Wurk Chicago Services offer is power washing / pressure washing services. Pressure washing in Barrington is not just ‘something we do, we are constantly researching new procedures and techniques to give you the best clean for your money. We are devoted to the business and your total satisfaction.  <br></br>
        We offer commercial and residential power washing services to anyone who would like to use our expert power washing services.''',
        "Powerwashing Meta": "Wurk Services Has Been Continuously Providing Highest Rated Pressure Washing Services in Chicago, Barrington Il, 60007, 60010. Our services include Power Washing, Pressure Washing, and Sanitation Services for our clients in Chicago, Barrington. We are fully committed to residential and commercial power washing services.",
        "Car Detail Meta": "Wurk Services Has Been Continuously Providing The Best Car Detailing & Washing Services in Barrington Il 60010. Our services include Interior and Exterior Car Detailing, Making Your Car Look Like New for our clients in Barrington. We are fully committed to making our cars look like new all the time.",
        "Car Detail": '''Wurk Services has been providing top of the line car detailing services for the Barrington and Greater Chicago Area. We are passionate about providing our customers with the highest quality car care, utilizing state-of-the-art auto detailing techniques, cutting edge products and a network of knowledge that is always being updated to make your car stand out. <br></br>
    Our talented team will work 1 on 1 with you to ensure that our car detailing project is always going as planned, and make sure that it fits your schedule too. <br></br>
    After serving many cars, we’ve seen it all and done it all. No job is too big or too small. Whether it be our ‘Ultra hand wash’ to complete reconditioning your car will reflect Wurk.''',
        "Academic Tutoring": "Our team of experienced educators and instructors provide one on one lessons in a plethora of areas ranging from math to computer science to reading.",
        "ACT and SAT Prep": "Live one-on-one SAT and ACT tutoring taught by experts from top universities. Our prep sessions provide proven strategies for time management and score maximization. You can receive guidance from one of our experts today for only $39 an hour",
        "Sports Coaching": " Recieve individual lessons in any sport from our seasoned coaches and trainers. Have your lesson within just a 24 hour notice of booking!",
        "Music Lessons": "Want to learn an instrument or just better your current understanding of an instrument? Wurk has tons of veteran musicians waiting to help you achieve your dreams. Make a booking now and achieve professional help at an affordable price!",
        "Construction": "Looking to build or maintain a property? Look no further, as Wurk construction services provide a full spectrum of services that can create the design of your dreams! From benches to treehouses, Wurk can construct, maintain, or restore any residential or commercial project!",
        "Pet Care": "Even pets get lonely some times, and that is where we come in! With Wurk pet care, we take care of your animals while you are out of the house! No animal is too big or small for us!",
        "House Sitting": "Rather not leave the house unattended? With Wurk, you will not have to! Wurk will treat your home as we treat our own, cleaning, and maintaining every facet of your estate. With affordable prices and highly flexible scheduling, it has never been easier to take care of your property!",
        "Deck and Roof Restoration": "A good deck and roof are the cornerstones of a great property. Do not let them fall into disarray. With Wurk Restoration services, we will turn any old deck or roof into a sight to behold!"

    }
