"""empty message

Revision ID: 16bf92a35405
Revises: 921f581e40b3
Create Date: 2020-06-18 12:59:38.170208

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '16bf92a35405'
down_revision = '921f581e40b3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('booked_days',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('day', sa.String(length=20), nullable=True),
    sa.Column('month', sa.String(length=15), nullable=True),
    sa.Column('wid', sa.String(length=10), nullable=True),
    sa.Column('jobtype', sa.String(length=30), nullable=True),
    sa.Column('peopleonjob', sa.String(length=200), nullable=True),
    sa.Column('time', sa.String(length=10), nullable=True),
    sa.Column('clientname', sa.String(length=30), nullable=True),
    sa.Column('name', sa.String(length=40), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('booking',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('clientname', sa.String(length=128), nullable=True),
    sa.Column('teachername', sa.String(length=128), nullable=True),
    sa.Column('typeofbooking', sa.String(length=128), nullable=True),
    sa.Column('comments', sa.String(length=1000), nullable=True),
    sa.Column('bookingid', sa.String(length=6), nullable=True),
    sa.Column('isclaimed', sa.Boolean(), nullable=True),
    sa.Column('claimedby', sa.String(length=30), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('bookingid')
    )
    op.create_table('client',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=True),
    sa.Column('email', sa.String(length=50), nullable=True),
    sa.Column('phonenumber', sa.String(length=50), nullable=True),
    sa.Column('address', sa.String(length=128), nullable=True),
    sa.Column('city', sa.String(length=128), nullable=True),
    sa.Column('state', sa.String(length=128), nullable=True),
    sa.Column('bookingid', sa.String(length=6), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('bookingid')
    )
    op.create_table('post',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pic', sa.String(length=128), nullable=True),
    sa.Column('title', sa.String(length=50), nullable=True),
    sa.Column('desc', sa.String(length=500), nullable=True),
    sa.Column('poster', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('time_sheet',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('timein', sa.String(length=128), nullable=True),
    sa.Column('timeout', sa.String(length=128), nullable=True),
    sa.Column('jobtype', sa.String(length=30), nullable=True),
    sa.Column('wurker', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('password', sa.String(length=128), nullable=True),
    sa.Column('isemployee', sa.Integer(), nullable=True),
    sa.Column('bio', sa.String(length=500), nullable=True),
    sa.Column('currenttimesheet', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_username'), 'user', ['username'], unique=True)
    op.create_table('booking_time',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('month', sa.String(length=20), nullable=True),
    sa.Column('day', sa.String(length=10), nullable=True),
    sa.Column('starttime', sa.String(length=10), nullable=True),
    sa.Column('bookingid', sa.String(length=6), nullable=True),
    sa.ForeignKeyConstraint(['bookingid'], ['booking.bookingid'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('personal_info',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=64), nullable=True),
    sa.Column('phonenumber', sa.String(length=128), nullable=True),
    sa.Column('address', sa.String(length=128), nullable=True),
    sa.Column('city', sa.String(length=128), nullable=True),
    sa.Column('state', sa.String(length=128), nullable=True),
    sa.Column('firstname', sa.String(length=128), nullable=True),
    sa.Column('lastname', sa.String(length=128), nullable=True),
    sa.Column('person', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['person'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('personal_info')
    op.drop_table('booking_time')
    op.drop_index(op.f('ix_user_username'), table_name='user')
    op.drop_table('user')
    op.drop_table('time_sheet')
    op.drop_table('post')
    op.drop_table('client')
    op.drop_table('booking')
    op.drop_table('booked_days')
    # ### end Alembic commands ###
