"""empty message

Revision ID: 1f82b4b0f11e
Revises: bab49b56e408
Create Date: 2020-05-12 19:13:18.099041

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1f82b4b0f11e'
down_revision = 'bab49b56e408'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('booking_time_bookingid_key', 'booking_time', type_='unique')
    op.drop_constraint('booking_time_bid_fkey', 'booking_time', type_='foreignkey')
    op.create_foreign_key(None, 'booking_time', 'booking', ['bookingid'], ['bookingid'])
    op.drop_column('booking_time', 'bid')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('booking_time', sa.Column('bid', sa.VARCHAR(length=6), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'booking_time', type_='foreignkey')
    op.create_foreign_key('booking_time_bid_fkey', 'booking_time', 'booking', ['bid'], ['bookingid'])
    op.create_unique_constraint('booking_time_bookingid_key', 'booking_time', ['bookingid'])
    # ### end Alembic commands ###
