"""Added forign key to post

Revision ID: 4cb0480a0adb
Revises: f8586dfcb7c8
Create Date: 2020-05-23 10:00:38.628331

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4cb0480a0adb'
down_revision = 'f8586dfcb7c8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('poster', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('post', 'poster')
    # ### end Alembic commands ###
