"""empty message

Revision ID: 4d1f50ebd068
Revises: ad463e3591c5
Create Date: 2020-05-12 18:59:51.475245

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4d1f50ebd068'
down_revision = 'ad463e3591c5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('booking_time', sa.Column('bid', sa.String(length=6), nullable=True))
    op.create_foreign_key(None, 'booking_time', 'booking', ['bid'], ['bookingid'])
    op.create_unique_constraint(None, 'client', ['bookingid'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'client', type_='unique')
    op.drop_constraint(None, 'booking_time', type_='foreignkey')
    op.drop_column('booking_time', 'bid')
    # ### end Alembic commands ###
