"""empty message

Revision ID: 6b97e9ff48f3
Revises: 534f0bf46acb
Create Date: 2020-05-12 14:25:31.692089

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6b97e9ff48f3'
down_revision = '534f0bf46acb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('booking',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('clientname', sa.String(length=128), nullable=True),
    sa.Column('teachername', sa.String(length=128), nullable=True),
    sa.Column('typeofbooking', sa.String(length=128), nullable=True),
    sa.Column('comments', sa.String(length=1000), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('booking_time',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('month', sa.String(length=20), nullable=True),
    sa.Column('day', sa.String(length=10), nullable=True),
    sa.Column('starttime', sa.String(length=10), nullable=True),
    sa.Column('endtime', sa.String(length=10), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('booking_time')
    op.drop_table('booking')
    # ### end Alembic commands ###
