"""empty message

Revision ID: 6d101af56099
Revises: d3f1d9e4f7b9
Create Date: 2020-05-22 00:38:41.651781

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6d101af56099'
down_revision = 'd3f1d9e4f7b9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('post',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pic', sa.String(length=128), nullable=True),
    sa.Column('desc', sa.String(length=128), nullable=True),
    sa.Column('wid', sa.String(length=10), nullable=True),
    sa.ForeignKeyConstraint(['wid'], ['wurker.wid'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('post')
    # ### end Alembic commands ###
