"""added job type to timesheet tabke

Revision ID: 6da70f637b43
Revises: febfa2969b7a
Create Date: 2020-05-25 15:00:55.111435

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6da70f637b43'
down_revision = 'febfa2969b7a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('time_sheet', sa.Column('jobtype', sa.String(length=30), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('time_sheet', 'jobtype')
    # ### end Alembic commands ###
