"""empty message

Revision ID: 81c241bf43d8
Revises: 1f82b4b0f11e
Create Date: 2020-05-12 19:56:16.128672

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '81c241bf43d8'
down_revision = '1f82b4b0f11e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('booked_days', sa.Column('name', sa.String(length=40), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('booked_days', 'name')
    # ### end Alembic commands ###
