"""empty message

Revision ID: 921f581e40b3
Revises: cf7fff675773
Create Date: 2020-05-30 09:28:51.713067

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '921f581e40b3'
down_revision = 'cf7fff675773'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('booking', sa.Column('claimedby', sa.String(length=30), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('booking', 'claimedby')
    # ### end Alembic commands ###
