"""added time sheet

Revision ID: b657bbc10e2f
Revises: 4cb0480a0adb
Create Date: 2020-05-25 14:46:09.203956

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b657bbc10e2f'
down_revision = '4cb0480a0adb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('time_sheet',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('timein', sa.String(length=128), nullable=True),
    sa.Column('timeout', sa.String(length=128), nullable=True),
    sa.Column('wurker', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('time_sheet')
    # ### end Alembic commands ###
