"""empty message

Revision ID: d235ba55acc6
Revises: 3f551b44b9eb
Create Date: 2020-05-12 16:33:05.204559

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd235ba55acc6'
down_revision = '3f551b44b9eb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('booking_time', 'endtime')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('booking_time', sa.Column('endtime', sa.VARCHAR(length=10), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
