"""empty message

Revision ID: d3f1d9e4f7b9
Revises: 61ad3e9e8ef9
Create Date: 2020-05-22 00:38:30.959670

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd3f1d9e4f7b9'
down_revision = '61ad3e9e8ef9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('wurker', sa.Column('bio', sa.String(length=500), nullable=True))
    op.add_column('wurker', sa.Column('password', sa.String(length=128), nullable=True))
    op.create_unique_constraint(None, 'wurker', ['wid'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'wurker', type_='unique')
    op.drop_column('wurker', 'password')
    op.drop_column('wurker', 'bio')
    # ### end Alembic commands ###
