"""empty message

Revision ID: dfe1e78153d0
Revises: 6faaa470e746
Create Date: 2020-05-12 18:45:22.874044

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dfe1e78153d0'
down_revision = '6faaa470e746'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('booked_days',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('day', sa.String(length=20), nullable=True),
    sa.Column('month', sa.String(length=15), nullable=True),
    sa.Column('wid', sa.String(length=10), nullable=True),
    sa.Column('jobtype', sa.String(length=30), nullable=True),
    sa.Column('peopleonjob', sa.String(length=200), nullable=True),
    sa.Column('time', sa.String(length=10), nullable=True),
    sa.Column('clientname', sa.String(length=30), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('wurker',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('wid', sa.String(length=10), nullable=True),
    sa.Column('fullname', sa.String(length=30), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('wurker')
    op.drop_table('booked_days')
    # ### end Alembic commands ###
