"""removed wurker table

Revision ID: f8586dfcb7c8
Revises: cde06f895469
Create Date: 2020-05-23 09:00:56.801631

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f8586dfcb7c8'
down_revision = 'cde06f895469'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('wurker')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('wurker',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('wid', sa.VARCHAR(length=10), autoincrement=False, nullable=True),
    sa.Column('fullname', sa.VARCHAR(length=30), autoincrement=False, nullable=True),
    sa.Column('bio', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('password', sa.VARCHAR(length=128), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='wurker_pkey'),
    sa.UniqueConstraint('wid', name='wurker_wid_key')
    )
    # ### end Alembic commands ###
