"""added time sheet for user

Revision ID: febfa2969b7a
Revises: b657bbc10e2f
Create Date: 2020-05-25 14:57:20.882446

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'febfa2969b7a'
down_revision = 'b657bbc10e2f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('currenttimesheet', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'currenttimesheet')
    # ### end Alembic commands ###
